apiVersion: apps/v1
kind: Deployment
metadata:
  name: ism-app
  namespace: kubernetes-dashboard
  labels:
    app: ism
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ism
  template:
    metadata:
      labels:
        app: ism
    spec:
      containers:
        - name: ism-container
          image: yamzhan/ism-demov1:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
      env:
        - name: DATABASE_URL
          value: "mysql+pymysql://root:OOqohPjpZZvNmGtSQyDXMWSWdAXbLQZp@metro.proxy.rlwy.net:46656/railway"