apiVersion: v1
kind: Service
metadata:
  name: ism-service
  namespace: kubernetes-dashboard
  labels:
    app: ism
spec:
  type: NodePort
  selector:
    app: ism
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
