apiVersion: v1
kind: Service
metadata:
  name: ism-service
  labels:
    app: ism
spec:
  type: NodePort  # You can change to LoadBalancer if using cloud
  selector:
    app: ism
  ports:
    - port: 8000       # Kubernetes service port
      targetPort: 8000 # Container port
      nodePort: 30080  # Accessible from host/node (e.g. http://localhost:30080)